name: Static analysis

on:
 workflow_call:
 inputs:
    php-versions:
     required: true
     type: string
jobs:
  phpstan:
   
    name: PHPStan 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ${{ fromJSON(inputs.php-versions) }}
        stability: [prefer-lowest, prefer-stable]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: phpstan

      - name: Execute PHPStan
        run: phpstan analyze --no-progress

  php-codesniffer:
   
    name: PHP-CodeSniffer - ${{ matrix.php }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: php-cs-fixer, phpcs
      - name: Execute PHP CodeSniffer
        run: phpcs -q

  psalm:
    
    name: Psalm - ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ${{ fromJSON(inputs.php-versions) }}
        stability: [prefer-lowest, prefer-stable]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, intl
          tools: vimeo/psalm
          
      - name: Setup composer
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress


      - name: Execute Psalm
        run: psalm --no-progress --output-format=github --root=${GITHUB_WORKSPACE}
